server:
  port: 8888
spring:
  application:
    name: config-java8
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mselucas/configRepo
          default-label: master
